version: "3.7"
services:
  www:
    build:
      context: ./
      dockerfile: apache2.Dockerfile
    ports:
      - 8005:80
      - 9005:443
    networks:
      - default
    depends_on:
      - mysql
    volumes:
      - ./html/:/var/www/html/
  mysql:
    image: mysql:latest
    networks:
      - default
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mjythn
    volumes:
      - ./db_data/:/var/lib/mysql/
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
        - 8006:80
     depends_on:
        - mysql
     environment:
        PMA_HOST: mysql
     networks:
        - default
networks:
  default: