version: "3.7"
services:
  php:
    build:
      context: ./
      dockerfile: apache2.Dockerfile
    ports:
      - 8005:80
      - 9005:90
    networks:
      - php
    volumes:
      - ./html/:/var/www/html/
  mysql:
    image: mysql:latest
    networks:
      - php
    environment:
      - MYSQL_ROOT_PASSWORD=mjythn
networks:
  php: